CREATE OR REPLACE PROCEDURE PROC_ALTA(MAT VARCHAR2, FUNC VARCHAR2)
AS
RESULTADO BOOLEAN;
BEGIN
    RESULTADO:=Busca_Matricula(MAT);
    
    IF RESULTADO IS FALSE THEN
        VER('NO EXISTE LA MATRICULA')
    ELSE
        INSERT INTO COCHES_TALLER
        
END;