CREATE OR REPLACE PROCEDURE TIPO_PROCEDIMIENTO(TIPO_OP CHAR,MATRIC VARCHAR2,FUNC VARCHAR2,TOTAL NUMBER)
AS
ERROR_EXCEPTION EXCEPTION;
BEGIN

    IF TIPO_OP = 'A' THEN
        PROC_ALTA(MATRIC,FUNC);
    ELSE
        IF TIPO_OP = 'T' THEN
        TERM_CHAMBA(MATRIC,TOTAL);
    ELSE
        RAISE ERROR_EXCEPTION;
    END IF;
        
EXCEPTION
WHEN ERROR_EXCEPTION THEN
    VER('NOSE');
    
END;