/*Procedimiento que muestra los datos de los veterinarios de la clínica*/

CREATE OR REPLACE PROCEDURE MOSTRAR_VETERINARIOS
AS
  
  CURSOR VETERINARIA IS
  SELECT * FROM VETERINARIOS;

BEGIN

  FOR I IN VETERINARIA LOOP
    VER(I.NUMCOLEGIADO || ' ' || I.NOMBRE || ' ' || I.TELEFONO);
  END LOOP; 

END;
SET SERVEROUTPUT ON;

EXECUTE MOSTRAR_VETERINARIOS;