CREATE OR REPLACE PROCEDURE INFO_COCHE
AS
    MATR VARCHAR2(20);

    CURSOR COCHE IS
        SELECT * FROM COCHES_TALLER;
    
    CURSOR ARREG (P_MATR VARCHAR2) IS
        SELECT FECHA_SALIDA, IMPORTE
        FROM ARREGLOS
        WHERE MATRICULA = P_MATR
        ORDER BY FECHA_SALIDA
        FETCH FIRST 1 ROW ONLY;

BEGIN

    FOR I IN COCHE LOOP
        VER (I.MATRICULA);
        MATR := I.MATRICULA;
        
        FOR J IN ARREG(MATR) LOOP
            VER (J.FECHA_SALIDA || ' ' || J.IMPORTE);
        END LOOP;
    END LOOP;

END;

EXECUTE INFO_COCHE;